/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as MTagRouteImport } from './routes/m.$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const MTagRoute = MTagRouteImport.update({
  id: '/m/$tag',
  path: '/m/$tag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/maps': typeof MapsRoute
  '/meta': typeof MetaRoute
  '/m/$tag': typeof MTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/maps': typeof MapsRoute
  '/meta': typeof MetaRoute
  '/m/$tag': typeof MTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/maps': typeof MapsRoute
  '/meta': typeof MetaRoute
  '/m/$tag': typeof MTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/ladder' | '/maps' | '/meta' | '/m/$tag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/ladder' | '/maps' | '/meta' | '/m/$tag'
  id: '__root__' | '/' | '/about' | '/ladder' | '/maps' | '/meta' | '/m/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LadderRoute: typeof LadderRoute
  MapsRoute: typeof MapsRoute
  MetaRoute: typeof MetaRoute
  MTagRoute: typeof MTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$tag': {
      id: '/m/$tag'
      path: '/m/$tag'
      fullPath: '/m/$tag'
      preLoaderRoute: typeof MTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LadderRoute: LadderRoute,
  MapsRoute: MapsRoute,
  MetaRoute: MetaRoute,
  MTagRoute: MTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
