/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as MTagRouteImport } from './routes/m.$tag'
import { Route as MapsIndexRouteImport } from './routes/maps.index'
import { Route as MapsMapRouteImport } from './routes/maps.$map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MTagRoute = MTagRouteImport.update({
  id: '/m/$tag',
  path: '/m/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsIndexRoute = MapsIndexRouteImport.update({
  id: '/maps/',
  path: '/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapRoute = MapsMapRouteImport.update({
  id: '/maps/$map',
  path: '/maps/$map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/meta': typeof MetaRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/m/$tag': typeof MTagRoute
  '/maps/$map': typeof MapsMapRoute
  '/maps/': typeof MapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/meta': typeof MetaRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/m/$tag': typeof MTagRoute
  '/maps/$map': typeof MapsMapRoute
  '/maps': typeof MapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ladder': typeof LadderRoute
  '/meta': typeof MetaRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/m/$tag': typeof MTagRoute
  '/maps/$map': typeof MapsMapRoute
  '/maps/': typeof MapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ladder'
    | '/meta'
    | '/settings'
    | '/stats'
    | '/m/$tag'
    | '/maps/$map'
    | '/maps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ladder'
    | '/meta'
    | '/settings'
    | '/stats'
    | '/m/$tag'
    | '/maps/$map'
    | '/maps'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ladder'
    | '/meta'
    | '/settings'
    | '/stats'
    | '/m/$tag'
    | '/maps/$map'
    | '/maps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LadderRoute: typeof LadderRoute
  MetaRoute: typeof MetaRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  MTagRoute: typeof MTagRoute
  MapsMapRoute: typeof MapsMapRoute
  MapsIndexRoute: typeof MapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$tag': {
      id: '/m/$tag'
      path: '/m/$tag'
      fullPath: '/m/$tag'
      preLoaderRoute: typeof MTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/': {
      id: '/maps/'
      path: '/maps'
      fullPath: '/maps/'
      preLoaderRoute: typeof MapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$map': {
      id: '/maps/$map'
      path: '/maps/$map'
      fullPath: '/maps/$map'
      preLoaderRoute: typeof MapsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LadderRoute: LadderRoute,
  MetaRoute: MetaRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  MTagRoute: MTagRoute,
  MapsMapRoute: MapsMapRoute,
  MapsIndexRoute: MapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
